name: Peer Video Player Release

on:
  push:
    # 只在拥有 v 开头的 tag 时触发 action
    tags: ['v*']

jobs:
  build-mac:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build
        run: |
          npm i -g pnpm
          pnpm install
          pnpm run build:mac

      - name: Release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: |
            *.dmg

  build-windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build
        run: |
          npm i -g pnpm
          pnpm install
          pnpm run build:win

      - name: Release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: |
            *.exe
